# Importing the libraries

In [112]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset

In [133]:
dataset = pd.read_csv('train.csv')
X = dataset.iloc[:, np.r_[2,4:8,9,11]].values
y = dataset.iloc[:, 1].values

In [114]:
print(X) 

[[3 'male' 22.0 ... 0 7.25 'S']
 [1 'female' 38.0 ... 0 71.2833 'C']
 [3 'female' 26.0 ... 0 7.925 'S']
 ...
 [3 'female' nan ... 2 23.45 'S']
 [1 'male' 26.0 ... 0 30.0 'C']
 [3 'male' 32.0 ... 0 7.75 'Q']]


In [115]:
print(X[0,:])

[3 'male' 22.0 1 0 7.25 'S']


In [116]:
print(y)

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 

In [117]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

## Load test set 

In [139]:
test_set = pd.read_csv('test.csv')
X_test = test_set.iloc[:, np.r_[1,3:9,10]].values

In [140]:
X_test

array([[3, 'male', 34.5, ..., '330911', 7.8292, 'Q'],
       [3, 'female', 47.0, ..., '363272', 7.0, 'S'],
       [2, 'male', 62.0, ..., '240276', 9.6875, 'Q'],
       ...,
       [3, 'male', 38.5, ..., 'SOTON/O.Q. 3101262', 7.25, 'S'],
       [3, 'male', nan, ..., '359309', 8.05, 'S'],
       [3, 'male', nan, ..., '2668', 22.3583, 'C']], dtype=object)

## Check if there is missing data

In [88]:
dataset.isnull().values.any()

True

In [119]:
test_set.isnull().values.any()

True

## Which columns are missing data

# Taking care of missing data

In [120]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') 
imputer.fit(X[:,2:3])
X[:,2:3] = imputer.transform(X[:,2:3])

In [121]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') 
imputer.fit(X_test[:,2:3])
X_test[:,2:3] = imputer.transform(X_test[:,2:3])

In [87]:
X[:,2:3]

array([[22.0],
       [38.0],
       [26.0],
       [35.0],
       [35.0],
       [29.69911764705882],
       [54.0],
       [2.0],
       [27.0],
       [14.0],
       [4.0],
       [58.0],
       [20.0],
       [39.0],
       [14.0],
       [55.0],
       [2.0],
       [29.69911764705882],
       [31.0],
       [29.69911764705882],
       [35.0],
       [34.0],
       [15.0],
       [28.0],
       [8.0],
       [38.0],
       [29.69911764705882],
       [19.0],
       [29.69911764705882],
       [29.69911764705882],
       [40.0],
       [29.69911764705882],
       [29.69911764705882],
       [66.0],
       [28.0],
       [42.0],
       [29.69911764705882],
       [21.0],
       [18.0],
       [14.0],
       [40.0],
       [27.0],
       [29.69911764705882],
       [3.0],
       [19.0],
       [29.69911764705882],
       [29.69911764705882],
       [29.69911764705882],
       [29.69911764705882],
       [18.0],
       [7.0],
       [21.0],
       [49.0],
       [29.0],
       [65.0],

In [130]:
len(X_test[:,0])

891

## Taking care of categorical missing data 

In [100]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imp.fit(X[:,6:7])
X[:,6:7] = imp.transform(X[:,6:7])

In [110]:
imp = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imp.fit(X_test[:,6:7])
X_test[:,6:7] = imp.transform(X_test[:,6:7])

# Encoding categorical data

# Encoding the Independent Variable 

In [103]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1,6])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [108]:
X[0,:]

array([0.0, 1.0, 0.0, 0.0, 1.0, 3, 22.0, 1, 0, 7.25], dtype=object)

## Feature scaling 

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X[:, [6,9]] = sc.fit_transform(X[:, [6,9]])
X_test[:, [6,9]] = sc.transform(X_test[:, [6,9]])

## Probe the dataset

In [104]:
dataset.head().columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [51]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

## Train the Model on the training set 

In [106]:
from sklearn.ensemble import RandomForestClassifier
RFC = RandomForestClassifier()
RFC.fit(X,y)

RandomForestClassifier()

## Probe model performance with test set